export type Variety = {
  [key: string]: Array<string>;
};

export type Category = {
  [key: string]: Array<Variety>;
};

export const data: Array<Category> = [
  {
    vegetables: [
      {
        cucumber: [
          "green fingers",
          "bush slicer",
          "beit alpha",
          "marketmore 76",
        ],
      },
      {
        beans: [
          "cantare",
          "dragon tongue",
          "soup mix blend",
          "french mascotte",
        ],
      },
      { "soy bean": ["chiba green"] },
      { "lima bean": ["henderson's bush"] },
      {
        beets: [
          "golden",
          "chioggia",
          "garden party",
          "five color rainbow",
          "gourmet golden",
          "easter egg",
        ],
      },
      {
        peas: [
          "sugar bon",
          "lillian's caseload",
          "alaska early",
          "magnolia blossom tendril",
        ],
      },
      {
        carrots: [
          "black nebula",
          "amarillo",
          "kyoto red",
          "harlequin mix",
          "purple sun",
          "circus circus",
          "longue rouge sang",
          "danvers",
          "nantes",
          "st valery",
          "uzbek golden",
        ],
      },
      {
        tomato: [
          "litchi",
          "rainbow heirloom blend",
          "vivacious hybrid",
          "bliss hybrid",
          "italian ice hybrid",
          "roma grande",
          "spoon",
          "pink tiger",
          "brandywine",
          "inca jewels",
          "italian san marzano",
          "black strawberry",
          "sweet treats",
          "roma VF",
          "alice's dream",
          "black beauty",
          "indigo blue berries",
          "chadwick cherry",
          "striped",
        ],
      },
      {
        tomatillo: ["two color fiesta", "miltomate", "verde"],
      },
      {
        peppers: [
          "aji mango",
          "cajun bell",
          "fish",
          "candy cane",
          "crimson, gold, & orange bell",
          "pizza my heart",
          "aji crystal",
          "datil",
          "serrano",
          "early flame jalapenos",
          "mocha swirl hybrid",
          "california wonder",
          "sugar rush peach",
          "italian sunset mix",
          "gourmet orange bell",
          "rainbow jalapeno spice trio",
          "habenero orange & red suave",
          "sweet rainbow blend bell",
          "cayenne blend",
          "tobago seasoning",
          "leutschauer paprika",
          "cayenne long thin",
          "hot salsa blend",
          "aji cachucha",
          "pippins golden honey",
          "aji habenero",
          "bullnose bell",
          "mini bell mix",
        ],
      },
      {
        lettuce: [
          "gustav's salad",
          "crispy winter greens",
          "summer glory blend",
          "little gem",
          "jericho romaine",
          "garden babies butterhead",
        ],
      },
      { kale: ["blue curled scotch", "garden blend", "purple moon"] },
      { cabbage: ["tete noire", "glory of enkhuizen"] },
      { arugala: ["wasabi"] },
      { chard: ["garden rainbow", "bright lights"] },
      { spinach: ["bloomsdale long standing", "little hero"] },
      {
        "brussel sprouts": [
          "red rubine",
          "groninger",
          "dagan hybrid",
          "hestia",
        ],
      },
      {
        cauliflower: [
          "purple crush",
          "rober",
          "purple of sicily",
          "flame star",
        ],
      },
      { broccoli: ["bravado", "calabrese green sprouting"] },
      { asparagus: ["mary washington"] },
      { celery: ["d'eline", "merlin"] },
      { eggplant: ["patio baby"] },
      { radish: ["gumball blend", "easter egg II"] },
      { corn: ["hopi blue", "glass gem", "orchard baby"] },
      { "bok choy": ["hedou tiny"] },
      { mizuna: ["beni houshi"] },
      { scallions: ["sprint", "delicious duo"] },
      {
        onion: [
          "australian brown",
          "golden sweet spanish",
          "rainbow trio",
          "rossa lunga di firenze",
        ],
      },
      { shallot: ["zebrune", "echalion hybrid"] },
    ],
  },
  {
    grains: [
      { barley: ["purple karma"] },
      { quinoa: ["cherry vanilla"] },
      { buckwheat: ["rose red soba"] },
    ],
  },
  {
    fruits: [
      { canteloupe: ["sugar cube", "hale's best jumbo"] },
      {
        strawberry: [
          "heirloom pineapple",
          "white soul",
          "rainbow treasure",
          "alexandria",
        ],
      },
      { honeydew: ["bodacious hybrid", "papaya"] },
      { watermelon: ["crimson sweet", "lemon drop"] },
      { "ground cherry": ["aunt molly's"] },
      {
        melon: [
          "mango hybrid",
          "superball hybrid",
          "rich sweetness 132",
          "hara madhu",
        ],
      },
      { huckleberry: ["garden"] },
      { banana: ["pink"] },
    ],
  },
  {
    flowers: [
      {
        impatiens: [
          "solarscape orange",
          "solarscape salmon",
          "solarscape white shimmer",
          "wallerina super",
          "xtreme utopia mix",
        ],
      },
      {
        periwinkle: [
          "titan mix",
          "tattoo raspberry",
          "tatoo black cherry",
          "tattoo tangerine",
          "tattoo papaya",
          "dwarf little delicata",
          "jams n' jellies blackberry",
        ],
      },
      {
        vinca: ["heatwave apricot", "pacifica mix", "vitesse patriot"],
      },
      {
        strawflower: [
          "tom thumb",
          "silvery rose",
          "rainbow bouquet",
          "color blend",
        ],
      },
      {
        "bachelors button": [
          "classic romantic",
          "blue boy",
          "classic artistic mix",
          "classic magic",
          "black button",
          "tall mix",
        ],
      },
      { dianthus: ["spooky mix", "raspberry ripple", "corona strawberry"] },
      { carnation: ["benigna", "picotee", "grenadin double"] },
      { scabiosa: ["formula mix"] },
      { cornflower: ["fantastic mix", "dwarf mix"] },
      { lavender: ["hidcote blue", "elegance pink", "torch minty ice"] },
      { achillea: ["summer berries"] },
      { centaurea: ["classic romantic"] },
      { "black eyed susan": ["blushing susie"] },
      {
        echinacea: [
          "paradiso mix",
          "green twister",
          "magnus",
          "cheyenne spirit",
        ],
      },
      { aster: ["matsumoto mix", "matsumoto red striped", "peony duchess"] },
      {
        petunia: [
          "tidal wave burgundy velour",
          "greetings from jaromere",
          "karkulka",
          "triumph mix",
          "superbissima giant rose",
          "superbissima giant alba",
          "superbissima cosmic cherry",
          "tidal wave pink hot",
          "veined mix",
          "celebrity mix",
          "double cascade mix",
          "easy wave beachcomber",
          "easy wave formula",
          "easy wave blue",
          "double glorious",
          "daddy mix",
          "evening scentsation hybrid",
          "tidal wave silver hybrid",
          "shock wave denim shades",
          "pirouette red",
          "opera supreme raspberry ice",
          "dreamwaves appleblossom",
        ],
      },
      {
        poppy: [
          "scarlet peony",
          "amazing grey",
          "mother of pearl",
          "falling in love",
          "rainbow mix california",
          "parks peony mix",
        ],
      },
      {
        nasturtium: [
          "ladybird rose",
          "chameleon",
          "little firebirds",
          "aloha mix",
        ],
      },
      { coreopsis: ["incredible dwarf"] },
      { dandelion: ["pink"] },
      { portulaca: ["double flowered", "sundial complete mix"] },
      { agastache: ["fragrant delight", "raspberry daiquiri", "rose mint"] },
      { "bee balm": ["spielarten mix"] },
      { gailardia: ["double sunset"] },
      { statice: ["soiree mix"] },
      {
        dahlia: [
          "blazing saddles",
          "dandy improved",
          "watercolor silks",
          "dandy",
        ],
      },
      { "ice plant": ["desert jewels"] },
      { "rose mallow": ["mix"] },
      {
        zinnia: [
          "zahara sunburst",
          "zinderella purple",
          "zinderella peach",
          "zinderella orange",
          "zinderella lilac",
          "zinderella red",
          "funfair mix",
          "queen red lime",
          "aztec sunset",
          "queen lime blush",
          "old mexico",
          "zahara starlight",
          "persian carpet",
          "summer pinwheels",
          "raspberry lemonade",
          "thumbelina mix",
          "profusion cherry bicolor",
          "profusion apricot",
          "peppermint stick",
          "whirligig",
          "hidden dragon",
          "candy mix",
          "aztec sunset",
        ],
      },
      {
        milkweed: [
          "showy",
          "common",
          "butterfly",
          "swamp pink",
          "swamp white",
          "autumn blaze blend",
        ],
      },
      { candytuft: ["fairy mix"] },
      { "blanket flower": ["single mix"] },
      { nemophilia: ["mixed"] },
      { "love in a mist": ["mixed colors"] },
      { toadflax: ["dwarf fairy mix"] },
      { primula: ["davona mixed", "sweet 16"] },
      { columbine: ["giant star"] },
      { cineraria: ["jester mix"] },
      { verbena: ["quartz xp mix"] },
      { feverfew: ["white stars"] },
      { aquilegia: ["kirigami mix"] },
      { alyssum: ["dwarf rainbow mix"] },
      { rudbeckia: ["cherry brandy"] },
      { phlox: ["lavender beauty"] },
      {
        "sweet pea": [
          "azureus blue",
          "mermaids dream",
          "mammoth mix",
          "spencer ruffled",
          "garden orchids",
          "color palette cupid",
          "saltwater taffy swirls",
        ],
      },
      {
        osteospermum: [
          "akila sunset",
          "akila grand canyon mix",
          "akila mix",
          "blue disc",
        ],
      },
      {
        "gerbera daisy": [
          "cartwheel strawberry twist mix",
          "revolution bicolor",
          "hybrid mix",
          "jaguar mix",
          "bicolor red lemonade",
        ],
      },
      { chrysanthemum: ["painted daisy"] },
      {
        cosmos: [
          "sensation mix",
          "apricotta",
          "xsenia",
          "rubinato",
          "apricot lemonade",
          "rosetta",
          "cherry pie",
          "capriola",
          "sonata mix",
        ],
      },
      {
        viola: [
          "laeta fire",
          "bowles black",
          "miniola heart aqua",
          "arkwright ruby",
          "admire blue",
          "jump up mix",
          "wine laeta",
          "envy",
        ],
      },
      {
        pansy: [
          "deluxxe orange",
          "swiss giant",
          "black devil",
          "trumpets mix",
          "celestial blue",
          "nature mulberry shades",
          "antique shades pink",
          "beaconsfield",
          "burgundy frizzle sizzle",
          "passionfruit frizzle sizzle",
          "light blue",
          "panola pink",
          "panola lilac",
          "flirty skirts",
          "delta pure",
          "blackberry mix",
          "spring fling mix",
          "chicky chicks",
          "victorian posy",
          "historic florist mix",
          "trumpets mix",
          "moulin rouge",
          "brush strokes",
        ],
      },
      {
        sunflower: [
          "paintbox bouquet",
          "snack seed",
          "ruby eclipse",
          "razzmataz mix",
          "mammoth",
          "autumn beauty",
          "tall sungold",
          "red sun",
          "lemon queen",
          "velvet queen",
        ],
      },
      { "four o'clock": ["broken colors"] },
      { sapiglossis: ["staind glass", "grandiflora mix"] },
      {
        marigold: [
          "strawberry blonde",
          "outback mix",
          "durango mix",
          "super hero mix",
          "fireball",
        ],
      },
      {
        snapdragon: [
          "chantilly summer flame",
          "snaptini mix",
          "floral showers bicolor mix",
        ],
      },
      { celosia: ["kimono formula mixed", "hippie tie dye"] },
      { gazania: ["sunshine mix", "big kiss"] },
    ],
  },
  {
    herbs: [
      { sage: ["culinary sage"] },
      { thyme: ["regular", "english", "orangelo"] },
      {
        basil: [
          "large leaf italian",
          "italian cameo",
          "cinnamon",
          "scented basil trio",
          "blue spice",
        ],
      },
      { mint: ["peppermint", "spearmint", "mountain"] },
      { "lemon balm": ["limoncello"] },
      { stevia: ["regular"] },
      { borage: ["regular"] },
      { "job's tears": ["regular"] },
      { rosemary: ["french"] },
      { parsley: ["italian large leaf"] },
      { oregano: ["heirloom italian"] },
    ],
  },
];
